meta_learner: vsm_net
meta_model: seq
learner_model: seq
learner_params:
  hidden_size: 256
  num_outputs:
    wsd: 5612
  embed_dim: 300
  dropout_ratio: 0

vsm_params:
  latent_dim: 128
  memory_size: 512
  beta: 1.0  
vectors: glove
meta_lr: 0.0005
learner_lr: 0.0005
vsm_weight: 0.5  
num_shots:
  wsd: 4
num_updates: 7
num_test_samples:
  wsd: 4
num_train_episodes:
  wsd: 10000
num_val_episodes:
  wsd: 166
num_test_episodes:
  wsd: 270
num_meta_epochs: 25
early_stopping: 2
device: cuda:0
proto_maml: false 